export const words = {
  en: {
    welcome:'Welcome back',loginSubtitle:'Sign in to manage the shared printer.',username:'Username',password:'Password',rememberMe:'Remember me',login:'Login',
    printerManager:'Printer Manager',home:'Home',queue:'Queue',favorites:'Favorite',inventory:'Inventory',statistics:'Statistics',history:'History',maintenance:'Maintenance',adminPanel:'Admin Panel',serverConnected:'Server connected',
    updates:'UPDATES',notifications:'Notifications',markAllRead:'Mark all as read',account:'ACCOUNT',settings:'Settings',changePassword:'Change password',currentPassword:'Current password',newPassword:'New password',confirmPassword:'Confirm password',updatePassword:'Update password',logout:'Logout',admin:'Admin',member:'Member',
    dashboard:'Dashboard',dashboardSubtitle:'A live view of the shared printer.',currentPrinting:'Current printing',printerStatus:'Printer status',timeRemaining:'Time remaining',queueCount:'Queue count',spools:'Filament spools',remainingGrams:'Remaining filament',printsMonth:'Prints this month',failedPrints:'Failed prints',canceledPrints:'Canceled prints',maintenanceCost:'Maintenance cost',idle:'Idle',printing:'Printing',paused:'Paused',noActivePrint:'No active print',queueHint:'Start the next job from the Queue page.',recentPrints:'Recent prints',yourSummary:'Your summary',requests:'Requests',activeQueue:'Active queue',favoriteItems:'Favorite items',totalPrints:'Total prints',successful:'Successful',gramsUsed:'Grams used',owner:'Owner',filament:'Filament',started:'Started',estimatedFinish:'Estimated finish',estimatedGrams:'Estimated grams',duration:'Duration',pause:'Pause',resume:'Resume',finish:'Finish',cancel:'Cancel',fail:'Fail',
    queueTitle:'Print queue',queueSubtitle:'Requests waiting for the shared printer.',addRequest:'Add request',search:'Search...',allOwners:'All owners',allStatuses:'All statuses',allPriorities:'All priorities',product:'Product',priority:'Priority',status:'Status',added:'Added',actions:'Actions',pending:'Pending',done:'Done',failed:'Failed',canceled:'Canceled',startPrinting:'Start printing',edit:'Edit',delete:'Delete',moveUp:'Up',moveDown:'Down',noQueue:'No queue requests',noQueueText:'Add the first print request.',
    favoriteTitle:'Favorite ideas',favoriteSubtitle:'Save models you want to print later.',addFavorite:'Add favorite',tags:'Tags',preferredFilament:'Preferred filament',moveToQueue:'Move to queue',noFavorites:'No favorite ideas',designSites:'Popular design sites',shopOnAmazon:'Shop PLA on Amazon',AliExpress:'Shop PLA on AliExpress',
    inventoryTitle:'Filament inventory',inventorySubtitle:'Track ownership, cost, and remaining material.',addFilament:'Add filament',material:'Material',color:'Color',owners:'Owners',remaining:'Remaining',pricePerGram:'Price / gram',usage:'Usage',normal:'Normal',lowFilament:'Low filament',empty:'Empty',viewLog:'Usage log',noFilaments:'No filaments found',
    statisticsTitle:'Statistics',statisticsSubtitle:'Printing and maintenance performance.',globalOverview:'Global overview',userPerformance:'User performance',successRate:'Success rate',totalConsumed:'Total consumed',mostUsedFilament:'Most used filament',mostUsedColor:'Most used color',mostActiveUser:'Most active user',maintenanceOverview:'Maintenance overview',repairs:'Repairs',upgrades:'Upgrades',parts:'Purchased parts',commonType:'Most common type',totalPaid:'Total paid',
    historyTitle:'Print history',historySubtitle:'Completed, failed, and canceled jobs.',allResults:'All results',result:'Result',date:'Date',note:'Note',noHistory:'No print history',
    maintenanceTitle:'Maintenance records',maintenanceSubtitle:'Repairs, upgrades, cleaning, and shared costs.',addMaintenance:'Add maintenance',allTypes:'All types',responsible:'Responsible user',store:'Store',cost:'Cost',description:'Description',lastMaintenance:'Last maintenance',mostExpensive:'Most expensive',noMaintenance:'No maintenance records',
    adminTitle:'Admin panel',adminSubtitle:'Permissions, data, and account controls.',currentAdmin:'Current Admin',transferAdmin:'Transfer Admin',transferWarning:'The current Admin will lose access immediately.',transfer:'Transfer access',dataTools:'Data tools',exportData:'Export JSON',importData:'Import JSON',resetData:'Reset app data',resetWarning:'This clears activity data and returns Admin access to Abdullah.',quickLinks:'Quick links',openInventory:'Open inventory',openHistory:'Open history',allNotifications:'All notifications',completed:'Completed',maintenance:'Maintenance',repair:'Repair','purchased part':'Purchased Part',upgrade:'Upgrade',cleaning:'Cleaning',calibration:'Calibration','consumable purchase':'Consumable Purchase',other:'Other',
    save:'Save',close:'Close',modelLink:'Model/file link',imageUrl:'Image URL',notes:'Notes',durationMinutes:'Duration (minutes)',selectFilament:'Select filament',low:'Low',high:'High',title:'Title',type:'Type',printer:'Printer',totalCost:'Total cost (SAR)',invoiceLink:'Invoice link',receiptImage:'Receipt image URL',amountPaid:'Amount paid',paymentsEqual:'Payments must equal the total cost.',purchaseDate:'Purchase date',totalWeight:'Total weight (g)',remainingWeight:'Remaining weight (g)',price:'Price (SAR)',colorHex:'Color preview',resultNote:'Result note / reason',actualGrams:'Actual or wasted grams',confirm:'Confirm',createdBy:'Created by',finishedBy:'Finished by',noData:'No data available',minutes:'min',grams:'g',sar:'SAR',view:'View'
  },
  ar: {
    welcome:'حياك من جديد',loginSubtitle:'سجّل دخولك لإدارة الطابعة المشتركة.',username:'اسم المستخدم',password:'كلمة المرور',rememberMe:'تذكرني',login:'تسجيل الدخول',
    printerManager:'إدارة الطابعة',home:'الرئيسية',queue:'الطابور',favorites:'المفضلة',inventory:'المخزون',statistics:'الإحصائيات',history:'السجل',maintenance:'الصيانة',adminPanel:'لوحة المدير',serverConnected:'الخادم متصل',
    updates:'التحديثات',notifications:'الإشعارات',markAllRead:'تحديد الكل كمقروء',account:'الحساب',settings:'الإعدادات',changePassword:'تغيير كلمة المرور',currentPassword:'كلمة المرور الحالية',newPassword:'كلمة المرور الجديدة',confirmPassword:'تأكيد كلمة المرور',updatePassword:'تحديث كلمة المرور',logout:'تسجيل الخروج',admin:'مدير',member:'عضو',
    dashboard:'لوحة التحكم',dashboardSubtitle:'عرض مباشر للطابعة المشتركة.',currentPrinting:'الطباعة الحالية',printerStatus:'حالة الطابعة',timeRemaining:'الوقت المتبقي',queueCount:'طلبات الطابور',spools:'بكرات الفيلمنت',remainingGrams:'الفيلمنت المتبقي',printsMonth:'طبعات هذا الشهر',failedPrints:'الطبعات الفاشلة',canceledPrints:'الطبعات الملغاة',maintenanceCost:'تكلفة الصيانة',idle:'متوقفة',printing:'تطبع',paused:'متوقفة مؤقتًا',noActivePrint:'لا توجد طباعة حالية',queueHint:'ابدأ المهمة التالية من صفحة الطابور.',recentPrints:'آخر الطبعات',yourSummary:'ملخص حسابك',requests:'الطلبات',activeQueue:'الطابور النشط',favoriteItems:'عناصر المفضلة',totalPrints:'إجمالي الطبعات',successful:'الناجحة',gramsUsed:'الجرامات المستخدمة',owner:'المالك',filament:'الفيلمنت',started:'وقت البدء',estimatedFinish:'النهاية المتوقعة',estimatedGrams:'الجرامات المتوقعة',duration:'المدة',pause:'إيقاف مؤقت',resume:'استئناف',finish:'إنهاء',cancel:'إلغاء',fail:'فشل الطباعة',
    queueTitle:'طابور الطباعة',queueSubtitle:'طلبات تنتظر الطابعة المشتركة.',addRequest:'إضافة طلب',search:'بحث...',allOwners:'كل المالكين',allStatuses:'كل الحالات',allPriorities:'كل الأولويات',product:'المنتج',priority:'الأولوية',status:'الحالة',added:'تاريخ الإضافة',actions:'الإجراءات',pending:'معلق',done:'مكتمل',failed:'فاشل',canceled:'ملغى',startPrinting:'بدء الطباعة',edit:'تعديل',delete:'حذف',moveUp:'رفع',moveDown:'خفض',noQueue:'لا توجد طلبات',noQueueText:'أضف أول طلب طباعة.',
    favoriteTitle:'الأفكار المفضلة',favoriteSubtitle:'احفظ المجسمات التي تريد طباعتها لاحقًا.',addFavorite:'إضافة للمفضلة',tags:'الوسوم',preferredFilament:'الفيلمنت المفضل',moveToQueue:'نقل للطابور',noFavorites:'لا توجد أفكار مفضلة',designSites:'أشهر مواقع التصاميم الجاهزة',shopOnAmazon:'تسوق PLA من أمازون',AliExpress:'تسوق PLA من علي إكسبريس',
    inventoryTitle:'مخزون الفيلمنت',inventorySubtitle:'تابع الملكية والتكلفة والكمية المتبقية.',addFilament:'إضافة فيلمنت',material:'المادة',color:'اللون',owners:'الملاك',remaining:'المتبقي',pricePerGram:'سعر الجرام',usage:'الاستخدام',normal:'طبيعي',lowFilament:'فيلمنت منخفض',empty:'فارغ',viewLog:'سجل الاستخدام',noFilaments:'لا توجد بكرات',
    statisticsTitle:'الإحصائيات',statisticsSubtitle:'أداء الطباعة والصيانة.',globalOverview:'النظرة العامة',userPerformance:'أداء المستخدمين',successRate:'نسبة النجاح',totalConsumed:'إجمالي الاستهلاك',mostUsedFilament:'الأكثر استخدامًا',mostUsedColor:'اللون الأكثر استخدامًا',mostActiveUser:'أنشط مستخدم',maintenanceOverview:'ملخص الصيانة',repairs:'الإصلاحات',upgrades:'الترقيات',parts:'القطع المشتراة',commonType:'النوع الأكثر تكرارًا',totalPaid:'إجمالي المدفوع',
    historyTitle:'سجل الطباعة',historySubtitle:'الطبعات المكتملة والفاشلة والملغاة.',allResults:'كل النتائج',result:'النتيجة',date:'التاريخ',note:'الملاحظة',noHistory:'لا يوجد سجل طباعة',
    maintenanceTitle:'سجل الصيانة',maintenanceSubtitle:'الإصلاحات والترقيات والتنظيف والتكاليف المشتركة.',addMaintenance:'إضافة صيانة',allTypes:'كل الأنواع',responsible:'المسؤول',store:'المتجر',cost:'التكلفة',description:'الوصف',lastMaintenance:'آخر صيانة',mostExpensive:'الأعلى تكلفة',noMaintenance:'لا توجد سجلات صيانة',
    adminTitle:'لوحة المدير',adminSubtitle:'الصلاحيات والبيانات وإدارة الحساب.',currentAdmin:'المدير الحالي',transferAdmin:'نقل صلاحية المدير',transferWarning:'المدير الحالي سيفقد صلاحياته مباشرة.',transfer:'نقل الصلاحية',dataTools:'أدوات البيانات',exportData:'تصدير JSON',importData:'استيراد JSON',resetData:'تصفير بيانات التطبيق',resetWarning:'يحذف بيانات النشاط ويعيد صلاحية المدير لعبدالله.',quickLinks:'روابط سريعة',openInventory:'فتح المخزون',openHistory:'فتح السجل',allNotifications:'كل الإشعارات',completed:'مكتملة',printing:'تطبع',paused:'متوقفة مؤقتًا',maintenance:'صيانة',repair:'إصلاح','purchased part':'قطعة مشتراة',upgrade:'ترقية',cleaning:'تنظيف',calibration:'معايرة','consumable purchase':'شراء مستهلكات',other:'أخرى',
    save:'حفظ',close:'إغلاق',modelLink:'رابط الملف/المجسم',imageUrl:'رابط الصورة',notes:'ملاحظات',durationMinutes:'المدة (بالدقائق)',selectFilament:'اختر الفيلمنت',low:'منخفضة',high:'عالية',title:'العنوان',type:'النوع',printer:'الطابعة',totalCost:'إجمالي التكلفة (ر.س)',invoiceLink:'رابط الفاتورة',receiptImage:'رابط صورة الإيصال',amountPaid:'المبلغ المدفوع',paymentsEqual:'يجب أن يساوي مجموع المدفوعات التكلفة الإجمالية.',purchaseDate:'تاريخ الشراء',totalWeight:'الوزن الإجمالي (جم)',remainingWeight:'الوزن المتبقي (جم)',price:'السعر (ر.س)',colorHex:'معاينة اللون',resultNote:'ملاحظة النتيجة / السبب',actualGrams:'الجرامات الفعلية أو المهدرة',confirm:'تأكيد',createdBy:'أضيف بواسطة',finishedBy:'أنهاها',noData:'لا توجد بيانات',minutes:'دقيقة',grams:'جم',sar:'ر.س',view:'عرض'
  }
};

export function fmtDate(value, language, includeTime = false) {
  if (!value) return '—';
  return new Intl.DateTimeFormat(
    language === 'ar' ? 'ar-SA' : 'en-GB',
    includeTime ? { dateStyle: 'medium', timeStyle: 'short' } : { dateStyle: 'medium' }
  ).format(new Date(value));
}

export function fmtNum(value, language, digits = 0) {
  return new Intl.NumberFormat(language === 'ar' ? 'ar-SA' : 'en-US', { maximumFractionDigits: digits }).format(Number(value || 0));
}
